name: "build"
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main
      - alpha

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      IMAGE: aelfactory/aelf-devcontainer
    steps:
      - name: Checkout (GitHub)
        uses: actions/checkout@v3

      - name: Test image builds correctly and is able to pass all tests
        uses: devcontainers/ci@v0.3
        with:
          cacheFrom: ${{ env.IMAGE }}
          push: never
          runCmd: |
            mkdir workshop &&
            cd workshop &&
            dotnet new aelf &&
            cd src &&
            dotnet build &&
            cd ../test &&
            dotnet test &&
            aelf-command -v &&
            aelf-deploy --version

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v4
        id: semantic
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to DockerHub
        if: steps.semantic.outputs.new_release_published == 'true'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and publish
        if: steps.semantic.outputs.new_release_published == 'true'
        uses: devcontainers/ci@v0.3
        with:
          imageName: ${{ env.IMAGE }}
          cacheFrom: ${{ env.IMAGE }}
          imageTag: ${{ steps.semantic.outputs.new_release_version }}${{ github.ref_name == 'main' && ',latest' || '' }}
          push: always
