name: "build"
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (GitHub)
        uses: actions/checkout@v3

      - name: Test image builds correctly and is able to pass all tests
        uses: devcontainers/ci@v0.3
        with:
          cacheFrom: ghcr.io/${{ github.repository_owner }}/aelfinity-workshop
          push: never
          runCmd: |
            mkdir workshop
            cd workshop
            dotnet new aelf
            cd src
            dotnet build
            cd ../test
            dotnet test
            aelf-command -v

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v4
        id: semantic
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        if: steps.semantic.outputs.new_release_published == 'true'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and publish
        if: steps.semantic.outputs.new_release_published == 'true'
        uses: devcontainers/ci@v0.3
        with:
          imageName: ghcr.io/${{ github.repository_owner }}/aelfinity-workshop
          cacheFrom: ghcr.io/${{ github.repository_owner }}/aelfinity-workshop
          imageTag: ${{ steps.semantic.outputs.new_release_version }}
          push: always
